version: '2'

services:
  app:
    build: .
    image: fteychene/dokcer-prez:compose
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - db
      - events
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jug
    expose:
      - 5432
    networks:
      - db
    volumes_from:
      - postgres-data
  postgres-data:
    image: alpine
    command: pwd > /dev/null
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
    networks:
      - events
networks:
  db:
    driver: bridge
  events:
      driver: bridge
