version: '2'

services:
  app:
    build: .
    image: fteychene/jee:compose
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - db
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jug
    expose:
      - 5432
    networks:
      db:
        aliases:
          - postgres
    volumes_from:
      - postgres-data
  postgres-data:
    image: alpine
    command: pwd > /dev/null
    volumes:
      - /var/lib/postgresql/data

networks:
  db:
    driver: bridge
