version: '2'

services:
  proxy:
    image: fteychene/docker-prez-proxy:swarm
    ports:
      - 8080:80
    networks:
      - front
  app:
    image: fteychene/docker-prez-app:swarm
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - 8080
    networks:
      - db
      - events
      - front
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jug
    expose:
      - 5432
    networks:
      - db
    volumes_from:
      - postgres-data
  postgres-data:
    image: alpine
    command: pwd > /dev/null
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
    networks:
      - events
networks:
  front:
  db:
  events:
